#!/bin/sh

bspc rule -r "*"

# Keyboard Settings
xset r on &
xset r rate 300 50 &
xset b off &
numlockx & # turns numlock on
setxkbmap pt & # keyboard language
setxkbmap -option caps:swapescape & # swaps capslock with esc key

# Start Keybindings and Polybar
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/polybar-launch.sh &

pgrep bspswallow || ~/Docs/Scripts/bspswallow &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7

#bspc config automatic_scheme spiral
~/Docs/Scripts/masterlayout &

bspc config border_width           2
bspc config window_gap             10
bspc config top_padding            0
bspc config bottom_padding         0
bspc config left_padding           0
bspc config right_padding          0
bspc config click_to_focus         true
bspc config focus_follows_pointer  false
bspc config split_ratio            0.25
bspc config borderless_monocle     true
bspc config gapless_monocle        true

# Desktop Rules
bspc rule -a LibreWolf desktop='^2' state=monocle follow=on
bspc rule -a Chromium desktop='^2' state=monocle follow=on
bspc rule -a KeePassXC desktop='^7' state=titled follow=on
bspc rule -a Pcmanfm desktop='^3' state=titled follow=on
bspc rule -a TelegramDesktop desktop='^4' state=titled follow=on
bspc rule -a "Microsoft Teams - Preview" desktop='^7' state=titled follow=off
bspc rule -a discord desktop='^7' state=titled follow=on

# Floating Apps
bspc rule -a Gpick state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a Lightdm-gtk-greeter-settings state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Grub-customizer state=floating
bspc rule -a flameshot state=floating
bspc rule -a Nvidia-settings state=floating
bspc rule -a GParted state=floating
bspc rule -a PacketTracer state=floating
bspc rule -a Galculator state=floating
bspc rule -a Blueberry.py state=floating

# Border Colors
bspc config normal_border_color \#0d0d0d
bspc config active_border_color \#0d0d0d
bspc config focused_border_color \#A0201A
bspc config presel_feedback_color \#A0201A
bspc config urgent_border_color \#689D6A

# Paywal Colors
# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Border colors
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"

sleep 2 && ~/Docs/Scripts/check_updates && polybar-msg hook updates 1 &
